# Generated by Django 6.0.2 on 2026-02-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约用户'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booker',
            field=models.CharField(max_length=100, verbose_name='预约人姓名'),
        ),
    ]
