# Generated by Django 6.0.2 on 2026-02-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservation_status_reservation_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '自习室', 'verbose_name_plural': '自习室'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('self_study', '自习用教室'), ('computer', '电脑自习室'), ('book', '图书自习室')], default='self_study', max_length=20, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_rooms', to=settings.AUTH_USER_MODEL, verbose_name='管理员(教师)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='院系/班级'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room', verbose_name='自习室'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='用途/主题'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='自习室名称'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='booking.room', verbose_name='所属自习室')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.equipment', verbose_name='设备'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='座位号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.room', verbose_name='所属自习室')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.seat', verbose_name='座位'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('admin', '管理员')], default='student', max_length=20, verbose_name='角色')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='学号/工号')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='院系')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
