# Generated by Django 6.0.2 on 2026-02-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_options_remove_room_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
            ],
            options={
                'verbose_name': '学生信息库',
                'verbose_name_plural': '学生信息库',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
            ],
            options={
                'verbose_name': '教师信息库',
                'verbose_name_plural': '教师信息库',
            },
        ),
    ]
